# Generated by Django 3.0.2 on 2020-01-29 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area_id',
            field=models.ForeignKey(db_column='area_id', default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.Area'),
        ),
    ]
