# Generated by Django 3.0.2 on 2020-01-29 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200129_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area_id',
            field=models.ForeignKey(blank=True, db_column='area_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Area'),
        ),
    ]
